Repository dnd-side-project/dnd-7th-10-frontend, pull requests merged in 2022-08, with the labels that each got.

#30 [#29] 패키지명/프로젝트 명 변경
  android/app/_BUCK
  android/app/build.gradle
  android/app/src/debug/java/com/inandout/ReactNativeFlipper.java
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/me/linkkle/app/MainActivity.java
  android/app/src/main/java/me/linkkle/app/MainApplication.java
  android/app/src/main/java/me/linkkle/app/newarchitecture/MainApplicationReactNativeHost.java
  android/app/src/main/java/me/linkkle/app/newarchitecture/components/MainComponentsRegistry.java
  android/app/src/main/java/me/linkkle/app/newarchitecture/modules/MainApplicationTurboModuleManagerDelegate.java
  android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.h
  android/app/src/main/jni/MainComponentsRegistry.h
  android/app/src/main/res/values/strings.xml
  android/settings.gradle
  app.json
  ios/Linkkle.xcodeproj/project.pbxproj
  ios/Linkkle.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ios/Linkkle.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/Linkkle.xcodeproj/xcshareddata/xcschemes/Linkkle.xcscheme
  ios/Linkkle.xcworkspace/contents.xcworkspacedata
  ios/Linkkle/AppDelegate.h
  ios/Linkkle/AppDelegate.mm
  ios/Linkkle/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/Linkkle/Images.xcassets/Contents.json
  ios/Linkkle/Info.plist
  ios/Linkkle/LaunchScreen.storyboard
  ios/Linkkle/main.m
  ios/LinkkleTests/Info.plist
  ios/LinkkleTests/LinkkleTests.m
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  yarn.lock
Labels: epic

#44 [#43] react-navigation
  android/app/src/main/java/me/linkkle/app/MainActivity.java
  package.json
  yarn.lock
Labels: setup

#45 [#27] 홈 화면 개발 - 네비게이션 x
  src/assets/images/folder_1.png
  src/assets/images/folder_2.png
  src/assets/images/folder_3.png
  src/assets/images/folder_4.png
  src/assets/images/folder_5.png
  src/assets/images/folder_add_light.png
  src/assets/images/icon_mypage.png
  src/assets/images/icon_search.png
  src/assets/images/logo_colored.png
  src/components/FolderAdd.tsx
  src/components/FolderItem.tsx
  src/components/FolderList.tsx
  src/components/HomeTop.tsx
  src/components/SearchBar.tsx
  src/pages/Home.tsx
Labels: feature

#46 [#16] header component
  src/components/Header.tsx
  src/pages/LinkDesc/LinkDesc.tsx
  src/pages/WebView/WebView.tsx
Labels: feature

#51 [#49] 디자인 시스템 값 세팅
  src/styles/backgrounds.ts
  src/styles/flexbox.ts
  src/styles/fonts.ts
  src/styles/variable.ts
Labels: setup

#53 [#49] HOTFIX: flexbox justify-content 타입 수정
  src/styles/flexbox.ts
Labels: bug

#54 [#48] 공통 헤더 컴포넌트
  src/assets/images/chevron-left.png
  src/assets/images/edit.png
  src/assets/images/trash.png
  src/components/Header.tsx
Labels: feature

#55 [#28] 폴더 콘텐츠
  src/assets/images/link.png
  src/assets/images/search.png
  src/components/FolderContent/FolderCard.tsx
  src/components/FolderContent/FolderCardList.tsx
  src/pages/FolderContent.tsx
Labels: feature

#56 [#1] chore: lint staged only
  package.json
Labels: bug, setup

#57 [#25] 스플래시 상태 설정
  src/assets/images/login_image_logo.png
  src/components/KakaoLoginButton.tsx
  src/pages/Login.tsx
Labels: feature

#59 [#58] 폴더 컨텐츠 빈화면
  src/components/FolderContent/FolderEmpty.tsx
  src/pages/FolderContent.tsx
Labels: feature

#61 [#60] 링크 추가 화면 개발
  src/assets/images/folder_navy.png
  src/assets/images/folder_orange.png
  src/assets/images/folder_pink.png
  src/assets/images/folder_selected.png
  src/assets/images/folder_sky.png
  src/assets/images/folder_yellow.png
  src/assets/images/plus.png
  src/assets/images/tag_remove.png
  src/assets/images/tag_remove_white.png
  src/components/Input.tsx
  src/components/LinkAdd/FolderSelectItem.tsx
  src/components/LinkAdd/FolderSelectList.tsx
  src/components/LinkAdd/TagGuide.tsx
  src/components/SectionContent.tsx
  src/components/SectionTitle.tsx
  src/components/Tag.tsx
  src/components/TagList.tsx
  src/pages/LinkAdd.tsx
Labels: feature

#63 [#62] 관심사 폴더 분리
  src/assets/test.ts
  src/components/Common/Header.tsx
  src/components/Common/Input.tsx
  src/components/Common/SectionContent.tsx
  src/components/Common/SectionTitle.tsx
  src/components/Common/Tag.tsx
  src/components/Common/TagList.tsx
  src/components/Home/FolderAdd.tsx
  src/components/Home/FolderItem.tsx
  src/components/Home/FolderList.tsx
  src/components/Home/HomeTop.tsx
  src/components/Home/SearchBar.tsx
  src/components/Login/KakaoLoginButton.tsx
  src/components/test.ts
  src/pages/FolderContent.tsx
  src/pages/Home.tsx
  src/pages/LinkAdd.tsx
  src/pages/Login.tsx
  src/pages/test.ts
Labels: refactor

#65 [#64] fix: wrong props and add elevation
  src/components/Common/Header.tsx
Labels: bug

#69 [#68] HOTFIX: 컴포넌트 경로 오류
  App.tsx
  src/components/Common/Header.tsx
  src/components/Common/SectionTitle.tsx
Labels: bug

#67 [#66] 폴더 생성 개발
  src/components/FolderAdd/FolderColorItem.tsx
  src/components/FolderAdd/FolderColorList.tsx
  src/pages/FolderAdd.tsx
Labels: feature

#71 [#70] 디자인 시스템
  src/assets/images/check.png
  src/assets/images/warning.png
  src/components/Common/Button.tsx
  src/components/Common/ButtonGroup.tsx
  src/components/Common/Toast.tsx
Labels: setup

#76 [#75] svg 적용
  .svgrrc
  metro.config.js
  package.json
  src/assets/images/bell.svg
  src/assets/images/check.svg
  src/assets/images/chevron-left.svg
  src/assets/images/edit.svg
  src/assets/images/link.svg
  src/assets/images/member.svg
  src/assets/images/memo.svg
  src/assets/images/remove.svg
  src/assets/images/search.svg
  src/assets/images/svg.ts
  src/assets/images/warning.svg
  src/types/index.d.ts
  yarn.lock
Labels: setup

#77 [#40] 링크 상세 컨텐츠 보이기
  src/assets/images/bookmark.png
  src/assets/images/chevron-left.png
  src/assets/images/edit.png
  src/assets/images/icon_+.png
  src/assets/images/icon_edit.png
  src/assets/images/icon_link.png
  src/assets/images/icon_memo.png
  src/assets/images/icon_x.png
  src/assets/images/link_desc_thumbnail.png
  src/assets/images/trash.png
  src/components/LinkContent/LinkContent.tsx
  src/components/LinkContent/Memo.tsx
  src/components/LinkContent/MemoContent.tsx
  src/components/LinkContent/MemoTop.tsx
  src/components/LinkContent/Tag.tsx
  src/components/LinkContent/TagBar.tsx
  src/pages/Link.tsx
  src/pages/LinkContents.tsx
  src/pages/LinkDesc/LinkDesc.tsx
  src/pages/WebView/WebView.tsx
Labels: feature

#78 [#72] 바텀 네비게이션
  package.json
  src/assets/images/add.svg
  src/assets/images/folder.svg
  src/assets/images/reminding.svg
  src/assets/images/svg.ts
  src/components/Common/TabBar.tsx
  src/pages/Main.tsx
  yarn.lock
Labels: feature

#80 [#73] 기본 라우팅 - 1/3
  App.tsx
  package.json
  src/components/Common/TabBar.tsx
  src/components/Home/FolderAdd.tsx
  src/components/Home/FolderList.tsx
  src/components/Home/HomeTop.tsx
  src/components/Home/SearchBar.tsx
  src/components/Login/KakaoLoginButton.tsx
  src/pages/Login.tsx
  src/pages/Router.tsx
  yarn.lock
Labels: feature

#81 [#79] api 세팅
  package.json
  src/hooks/useAuth.ts
  src/lib/api.ts
  src/lib/keychain.ts
  src/lib/storage.ts
  src/pages/Login.tsx
  src/recoil/auth.ts
  src/recoil/index.ts
  yarn.lock
Labels: feature

#83 [#82] 폴더 조회 / 생성 api 세팅
  App.tsx
  src/assets/images/folder_cover_navy.png
  src/assets/images/folder_cover_orange.png
  src/assets/images/folder_cover_pink.png
  src/assets/images/folder_cover_sky.png
  src/assets/images/folder_cover_yellow.png
  src/components/Common/BottomButton.tsx
  src/components/Common/Header.tsx
  src/components/Common/Input.tsx
  src/components/FolderAdd/FolderColorItem.tsx
  src/components/FolderAdd/FolderColorList.tsx
  src/components/Home/FolderAdd.tsx
  src/components/Home/FolderItem.tsx
  src/components/Home/FolderList.hook.ts
  src/components/Home/FolderList.tsx
  src/hooks/useAuth.ts
  src/pages/FolderAdd.tsx
  src/pages/Home.tsx
  src/pages/Router.tsx
  src/recoil/folders.ts
Labels: feature

#85 [#84] refactor: update color_palette
  src/styles/variable.ts
Labels: feature

#86 [#31] github actions
  .github/workflows/android_build.yml
  android/app/build.gradle
  ios/Linkkle/Info.plist
  ios/LinkkleTests/Info.plist
  package.json
  yarn.lock
Labels: setup

#88 [#87] chore: add dependencies
  package.json
  yarn.lock
Labels: bug

#90 [#89] refactor: change setup-java version
  .github/workflows/android_build.yml
Labels: setup

#92 [#91] 링크 추가 라우팅
  src/components/Common/Input.tsx
  src/components/Common/SectionTitle.tsx
  src/components/Common/TabBar.tsx
  src/components/Common/Tag.tsx
  src/components/LinkAdd/FolderSelectItem.tsx
  src/components/LinkAdd/FolderSelectList.tsx
  src/pages/FolderAdd.tsx
  src/pages/LinkAdd.tsx
  src/pages/Router.tsx
Labels: feature

#96 [#95] 모달 개발
  src/assets/images/alert-circle.png
  src/components/Common/Modal.tsx
  src/hooks/useModal.ts
  src/pages/Router.tsx
  src/recoil/index.ts
  src/recoil/modal.ts
  src/styles/variable.ts
Labels: feature

#98 [#97] 폴더 컨텐츠 / 링크 추가
  src/components/Common/Input.tsx
  src/components/Common/TagList.tsx
  src/components/FolderContent/FolderCard.tsx
  src/components/FolderContent/FolderCardList.tsx
  src/components/Home/FolderList.tsx
  src/components/LinkAdd/FolderSelectList.tsx
  src/hooks/useApi.ts
  src/hooks/useArticleDetail.ts
  src/hooks/useFolderDetail.ts
  src/hooks/useRecoilApi.ts
  src/hooks/useTagList.ts
  src/pages/FolderContent.tsx
  src/pages/LinkAdd.tsx
  src/pages/Router.tsx
  src/recoil/folders.ts
  src/recoil/tags.ts
Labels: feature

#100 [#99] 리마인딩 알림
  src/assets/images/bookmark.svg
  src/assets/images/bookmark_filled.svg
  src/assets/images/memo.svg
  src/assets/images/reminding_notice_frame.png
  src/assets/images/svg.ts
  src/components/Common/Card.tsx
  src/components/Common/Empty.tsx
  src/components/Common/Header.tsx
  src/components/FolderContent/FolderCardList.tsx
  src/components/RemindingNotice/NoticeContent.tsx
  src/components/RemindingNotice/NoticeTop.tsx
  src/pages/RemindingNotice.tsx
Labels: feature

#102 [#101] 알람 설정
  src/assets/images/add.svg
  src/assets/images/add_light.svg
  src/assets/images/chevron-right.svg
  src/assets/images/svg.ts
  src/components/Common/DayPicker.tsx
  src/components/Common/Empty.tsx
  src/components/Common/Select.tsx
  src/components/Common/Switch.tsx
  src/components/Common/TimePicker.tsx
  src/components/FolderContent/FolderCardList.tsx
  src/components/RemindingNotice/NoticeContent.tsx
  src/components/RemindingSetup/RemindItem.tsx
  src/components/RemindingSetup/SetupContent.tsx
  src/components/RemindingSetup/SetupPicker.tsx
  src/components/RemindingSetup/SetupTop.tsx
  src/pages/RemindingNotice.tsx
  src/pages/RemindingSetup.tsx
  src/styles/backgrounds.ts
  src/utils/debounce.ts
Labels: feature

#104 [#103] 링크모으기 ui 개발
  src/assets/images/alert-circle-normal.png
  src/assets/images/folder_selected_fill.png
  src/assets/images/folder_selected_star.png
  src/components/Common/Card.tsx
  src/components/Common/Empty.tsx
  src/components/Common/Select.tsx
  src/components/RemindingGather/GatherArticleItem.tsx
  src/components/RemindingGather/GatherArticleList.tsx
  src/components/RemindingGather/GatherFolderItem.tsx
  src/components/RemindingGather/GatherFolderList.tsx
  src/components/RemindingSetup/SetupPicker.tsx
  src/pages/RemindingGather.tsx
  src/pages/RemindingSetup.tsx
Labels: feature

#107 [#105] 메인화면 라우팅 및 버그 수정
  src/components/Common/Header.tsx
  src/components/Common/Modal.tsx
  src/components/Common/TabBar.tsx
  src/components/FolderContent/FolderCardList.tsx
  src/components/LinkAdd/FolderSelectList.tsx
  src/hooks/useAuth.ts
  src/hooks/useHeaderEvent.ts
  src/hooks/useModal.ts
  src/pages/FolderContent.tsx
  src/pages/LinkAdd.tsx
  src/pages/Router.tsx
  src/recoil/folders.ts
  src/recoil/global.ts
  src/recoil/test.ts
Labels: feature

#109 [#108] fcm, 카카오 로그인 세팅
  App.tsx
  android/app/build.gradle
  android/app/google-services.json
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/values/strings.xml
  android/build.gradle
  package.json
  yarn.lock
Labels: feature

#111 [#110] 태그 api 연동
  src/assets/images/folder_cover_orange.png
  src/components/Common/Tag.tsx
  src/components/Common/TagList.tsx
  src/components/FolderContent/FolderCard.tsx
  src/hooks/useTagList.ts
  src/pages/LinkAdd.tsx
  src/recoil/folders.ts
  src/recoil/tags.ts
Labels: feature

#114 [#112] 토스트 적용 및 폴더 오류 수정
  App.tsx
  src/components/Common/Toast.tsx
  src/components/Common/ToastContainer.tsx
  src/components/Home/FolderList.tsx
  src/hooks/useAuth.ts
  src/hooks/useToast.ts
  src/pages/FolderAdd.tsx
  src/pages/LinkAdd.tsx
  src/pages/Login.tsx
  src/recoil/folders.ts
  src/recoil/global.ts
Labels: bug, feature

#117 [#116] 헤더 검색 입력창
  src/assets/images/search_close.png
  src/components/Common/Header.tsx
  src/components/Common/Input.tsx
Labels: feature

#119 [#118] feat: auto focus with forward-ref
  src/components/Common/Input.tsx
  src/pages/LinkAdd.tsx
Labels: feature

#121 [#120] 카카오 로그인 연동
  src/hooks/useAuth.ts
  src/lib/kakao.ts
  src/lib/keychain.ts
  src/pages/Login.tsx
Labels: feature

#123 [#122] 링크 상세 라우팅
  src/components/Common/Card.tsx
  src/components/Common/Empty.tsx
  src/components/Common/Tag.tsx
  src/components/Common/TagList.tsx
  src/components/FolderContent/FolderCard.tsx
  src/components/FolderContent/FolderCardList.tsx
  src/components/LinkContent/LinkContent.tsx
  src/components/LinkContent/Memo.tsx
  src/components/LinkContent/MemoContent.tsx
  src/components/LinkContent/MemoTop.tsx
  src/components/LinkContent/Tag.tsx
  src/components/LinkContent/TagBar.tsx
  src/components/Memo.tsx
  src/components/MemoContent.tsx
  src/hooks/useArticleDetail.ts
  src/hooks/useAuth.ts
  src/hooks/useRecoilApi.ts
  src/pages/LinkContents.tsx
  src/pages/Login.tsx
  src/pages/Router.tsx
  src/recoil/folders.ts
Labels: feature

#126 [#124] 클립보드 연동
  package.json
  src/assets/images/folder_stroke.svg
  src/assets/images/svg.ts
  src/components/Common/Input.tsx
  src/components/Home/FolderList.tsx
  src/components/Home/QuickLink.tsx
  src/lib/urlcheck.ts
  src/pages/FolderAdd.tsx
  src/pages/Home.tsx
  src/pages/LinkAdd.tsx
  src/recoil/global.ts
  yarn.lock
Labels: feature

#128 [#127] 리마인드 라우팅 및 데이터 반영
  .eslintrc.js
  src/components/Common/Card.tsx
  src/components/Common/DayPicker.tsx
  src/components/Common/Select.tsx
  src/components/Common/TimePicker.tsx
  src/components/FolderContent/FolderCard.tsx
  src/components/FolderContent/FolderCardList.tsx
  src/components/Remind/MemoCollection.tsx
  src/components/Remind/Notice.tsx
  src/components/Remind/RemindingList.tsx
  src/components/RemindingGather/GatherArticleItem.tsx
  src/components/RemindingGather/GatherArticleList.tsx
  src/components/RemindingGather/GatherFolderItem.tsx
  src/components/RemindingGather/GatherFolderList.tsx
  src/components/RemindingSetup/RemindItem.tsx
  src/components/RemindingSetup/SetupContent.tsx
  src/components/RemindingSetup/SetupPicker.tsx
  src/components/RemindingSetup/SetupTop.tsx
  src/pages/FolderContent.tsx
  src/pages/LinkAdd.tsx
  src/pages/Login.tsx
  src/pages/MemoPage.tsx
  src/pages/RemindMain.tsx
  src/pages/RemindingGather.tsx
  src/pages/RemindingSetup.tsx
  src/pages/Router.tsx
  src/recoil/folders.ts
Labels: feature

#130 [#129] 웹뷰 페이지 구현
  App.tsx
  package.json
  src/components/Common/BrowserHeader.tsx
  src/components/Common/DayPicker.tsx
  src/components/Common/Input.tsx
  src/components/RemindingSetup/SetupPicker.tsx
  src/pages/Browser.tsx
  src/pages/RemindingSetup.tsx
  src/pages/Router.tsx
  src/pages/WebView.tsx
  src/recoil/global.ts
  yarn.lock
Labels: feature

#132 [#131] 신규 번들 생성
  App.tsx
  android/app/build.gradle
  ios/Linkkle/Info.plist
  ios/LinkkleTests/Info.plist
  package.json
Labels: feature

#138 [#137] chore: add icon images
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round_adaptive_back.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round_adaptive_fore.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round_adaptive_back.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round_adaptive_fore.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round_adaptive_back.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round_adaptive_fore.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round_adaptive_back.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round_adaptive_fore.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round_adaptive_back.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round_adaptive_fore.png
Labels: setup

#142 [#141]
  App.tsx
  android/app/build.gradle
  ios/Linkkle/Info.plist
  ios/LinkkleTests/Info.plist
  package.json
  src/components/Common/DayPicker.tsx
  src/components/Remind/LinkCard.tsx
  src/components/Remind/RemindingList.tsx
  src/components/RemindingGather/GatherArticleItem.tsx
  src/components/RemindingList/RemindingCardList.tsx
  src/components/RemindingNotice/NoticeContent.tsx
  src/components/RemindingNotice/NoticeTop.tsx
  src/hooks/useAuth.ts
  src/lib/api.ts
  src/pages/Login.tsx
  src/pages/RemindMain.tsx
  src/pages/RemindingListPage.tsx
  src/pages/RemindingNotice.tsx
  src/pages/Router.tsx
  src/recoil/global.ts
Labels: feature
